# Generated by Django 2.2.5 on 2019-09-04 02:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification', models.IntegerField(default=719349679)),
                ('wins', models.IntegerField(default=0, null=True)),
                ('losses', models.IntegerField(default=0, null=True)),
                ('ties', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('banned', models.BooleanField(default=False)),
                ('byweek', models.IntegerField()),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='weeknumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weeknum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='weeklypicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 9, 3, 22, 21, 50, 383623))),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team', to='heisefootball.Teams')),
                ('picker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeklypicks', to='heisefootball.Pickers')),
                ('weeknum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='week', to='heisefootball.weeknumber')),
            ],
        ),
        migrations.CreateModel(
            name='matchups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_home', models.IntegerField(default=0)),
                ('score_away', models.IntegerField(default=0)),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='heisefootball.Teams')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='heisefootball.Teams')),
                ('weeknum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='heisefootball.weeknumber')),
            ],
        ),
    ]
