# Generated by Django 2.2.5 on 2019-09-06 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heisefootball', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchups',
            name='eid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickers',
            name='verification',
            field=models.IntegerField(default=242439564),
        ),
        migrations.AlterField(
            model_name='weeklypicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 5, 20, 2, 0, 750030)),
        ),
    ]
