# Generated by Django 2.2.3 on 2019-09-05 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heisefootball', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='eid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickers',
            name='verification',
            field=models.IntegerField(default=201193402),
        ),
        migrations.AlterField(
            model_name='weeklypicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 5, 18, 47, 47, 857706)),
        ),
    ]
