# Generated by Django 2.2.3 on 2019-09-05 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heisefootball', '0002_auto_20190905_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickers',
            name='verification',
            field=models.IntegerField(default=630854351),
        ),
        migrations.AlterField(
            model_name='weeklypicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 5, 18, 50, 55, 93169)),
        ),
    ]
