# Generated by Django 2.2.3 on 2019-09-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heisefootball', '0002_auto_20190905_2002'),
        ('heisefootball', '0005_auto_20190907_1438'),
    ]

    operations = [
    ]
