# Generated by Django 2.2.5 on 2019-09-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heisefootball', '0005_auto_20190907_1438'),
        ('heisefootball', '0002_auto_20190905_2002'),
    ]

    operations = [
    ]
