# Generated by Django 2.2.3 on 2019-09-15 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heisefootball', '0006_merge_20190915_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickers',
            name='verification',
            field=models.IntegerField(default=350444925),
        ),
        migrations.AlterField(
            model_name='weeklypicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 11, 44, 37, 2432)),
        ),
    ]
