# Generated by Django 2.2.3 on 2019-09-15 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heisefootball', '0007_auto_20190915_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickers',
            name='verification',
            field=models.IntegerField(default=871270304),
        ),
        migrations.AlterField(
            model_name='weeklypicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 12, 3, 27, 403638)),
        ),
    ]
