# Generated by Django 2.2.3 on 2019-11-12 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heisefootball', '0008_auto_20190915_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesag', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='pickers',
            name='verification',
            field=models.IntegerField(default=592764677),
        ),
        migrations.AlterField(
            model_name='weeklypicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 20, 17, 23, 501905)),
        ),
    ]
