# Generated by Django 2.2.7 on 2019-12-27 05:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('heisefootball', '0010_auto_20191111_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=19)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='weeknumber',
            name='endweek',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeknumber',
            name='finished',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pickers',
            name='verification',
            field=models.IntegerField(default=676520949),
        ),
        migrations.AlterField(
            model_name='weeklypicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 23, 17, 52, 105965)),
        ),
        migrations.AddField(
            model_name='weeknumber',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='years', to='heisefootball.Year'),
        ),
    ]
