# Generated by Django 2.2.5 on 2019-11-12 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heisefootball', '0010_auto_20191111_2018'),
        ('heisefootball', '0006_merge_20190911_0851'),
    ]

    operations = [
    ]
