# Generated by Django 2.2.5 on 2019-11-12 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heisefootball', '0011_merge_20191111_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickers',
            name='verification',
            field=models.IntegerField(default=152116901),
        ),
        migrations.AlterField(
            model_name='weeklypicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 22, 0, 58, 105490)),
        ),
    ]
