# Generated by Django 2.2.7 on 2019-12-27 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heisefootball', '0011_auto_20191226_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeknumber',
            name='endweek',
        ),
        migrations.AlterField(
            model_name='pickers',
            name='verification',
            field=models.IntegerField(default=183547074),
        ),
        migrations.AlterField(
            model_name='weeklypicks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 0, 55, 25, 192634)),
        ),
    ]
