# Generated by Django 2.2.5 on 2019-12-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heisefootball', '0012_auto_20191111_2200'),
        ('heisefootball', '0012_auto_20191227_0055'),
    ]

    operations = [
    ]
