# Generated by Django 5.1.6 on 2025-09-07 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pick",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 7, 23, 31, 22, 664533, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
