# Generated by Django 3.1.4 on 2021-08-13 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 13, 32, 42, 766703, tzinfo=utc)),
        ),
    ]
