# Generated by Django 5.1.6 on 2025-09-07 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_pick_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="week",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="pick",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 7, 23, 32, 12, 888246, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
