# Generated by Django 5.1.6 on 2025-09-07 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_week_last_updated_alter_pick_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pick",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 7, 23, 32, 15, 579293, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
