# Generated by Django 5.1.6 on 2025-09-07 23:57

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_alter_pick_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pick",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 7, 23, 57, 2, 190860, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="week",
            name="last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
