# Generated by Django 3.1.4 on 2021-08-13 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210813_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 13, 39, 55, 181764, tzinfo=utc)),
        ),
    ]
