# Generated by Django 3.1.4 on 2021-08-25 05:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210813_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='propic',
            field=models.ImageField(default=0, upload_to='propics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 5, 9, 51, 455349, tzinfo=utc)),
        ),
    ]
