# Generated by Django 3.1.4 on 2021-09-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_halloffame'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
