# Generated by Django 3.1.4 on 2021-09-08 15:51

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20210905_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='coach_away',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='coach_home',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='espnId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='qb_away',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='qb_home',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pick',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 15, 51, 48, 873390, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='week',
            name='week_type',
            field=models.TextField(choices=[('REG', 'REG'), ('PRE', 'PRE'), ('OFF', 'OFF'), ('POST', 'POST')], default='Regular Season'),
        ),
    ]
